I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 215, in script
    with Fade(3.0)
TypeError: Fade() takes at least 3 arguments (3 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 215, in script
    with Fade(3.0)
  File "/Users/shuhei.shogen/src/renpy-6.99.10-sdk/renpy/ast.py", line 1266, in execute
    renpy.exports.with_statement(trans, paired)
  File "/Users/shuhei.shogen/src/renpy-6.99.10-sdk/renpy/exports.py", line 1357, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/shuhei.shogen/src/renpy-6.99.10-sdk/renpy/display/core.py", line 1987, in do_with
    clear=clear)
  File "/Users/shuhei.shogen/src/renpy-6.99.10-sdk/renpy/display/core.py", line 2425, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "/Users/shuhei.shogen/src/renpy-6.99.10-sdk/renpy/display/core.py", line 2646, in interact_core
    new_widget=layers_root)
  File "/Users/shuhei.shogen/src/renpy-6.99.10-sdk/renpy/curry.py", line 38, in __call__
    **dict(self.kwargs.items() + kwargs.items()))
TypeError: Fade() takes at least 3 arguments (3 given)

Darwin-15.6.0-x86_64-i386-64bit
Ren'Py 6.99.10.1227
FirstRenpy 0.0
